[package]
name = "ravetable"
version = "0.1.0"
authors = ["Katherine Philip <katherinephilip98@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.4.0"
cpal = "0.13.3"
clap = { version = "2.33.3", default-features = false }

#samplerate for converting wavs to requested output at load
samplerate = "0.2.4"

tuix = { git = "https://github.com/SonicZentropy/tuix",  rev = "8b3ee66" }

log = "0.4.14"
fern = "0.6.0"

anyhow = "1.0.40"
num-traits = "0.2.14"
crossbeam-channel = "0.5.0"
once_cell = "1.7.2"
itertools = "0.10.0"

[target.'cfg(target_os = "windows")'.dependencies]
winapi = { version = "0.3", features = ["audiosessiontypes", "audioclient", "coml2api", "combaseapi", "debug", "devpkey", "handleapi", "ksmedia", "mmdeviceapi", "objbase", "profileapi", "std", "synchapi", "winbase", "winuser"] }
num-traits = { version = "0.2.6", optional = true }

[target.'cfg(any(target_os = "linux"))'.dependencies]
alsa = "0.5"
jack = { version = "0.6.5", optional = true }

[target.'cfg(target_os = "macos")'.dependencies]
